### ISSUE TITLE
分页问题 

### ISSUE THREAD

**Issue by wangjingyu** [lidatui/mmGrid#37]
var mmg = $('.mmg').mmGrid({
                    height: 480
                    , cols: cols
                    , url: '**ROOT**/index.php/Data/get_json'
                    , method: 'get'
                    , remoteSort:false                  //如何使用客服端排序需要改成true
                    //, items: items                    //客户端数据
                    , sortName: 'date'                  //排序的字段名。字段名的值为列模型设置的sortName或name中的值。
                    , sortStatus: 'desc'                //排序方向。
                    , multiSelect: true                 //数据使用本地对象数组
                    , checkCol: true                        //表格显示checkbox
                    , indexCol: true                    //列索引
                    , showBackboard: true           //是否显示背板  默认true
                    , nowrap: true                          //表格显示的数据超出列宽时是否换行。
                    , indexColWidth: 20                 //表格索引列宽度
                    , fullWidthRows: true               //true:表格第一次加载数据时列伸展，自动充满表格。
                    , autoLoad: true
                    , params:{Pa:'10'}

```
                , plugins: [
                    $('#pg').mmPaginator({})
                ]
```

代码如上，分页不好用，跟演示站一样，点击下一页时，只有列（indexCol）在动，而数据没有动，大神帮帮忙。看看这有啥问题

**Comment by github-project** [comment]
大神 分页如何实现的啊 可以把代码发给我看看吗
